#!/bin/bash
login=$1
password=$2
user=$3

ex=$(find . -regex '\./ex[0-9]*/ex[0-9].*' | cut -d'/' -f2,3 \
	| grep -v 'ex0[0-5]')
for i in $ex
do
	filename=$(echo $i | cut -d'/' -f2)
	query=$(cat $i) ; mysql -u $login -p$password -D db_$user -B -e "$query" > \
		piscine_php_d05_check/sql_test_dir/$filename.out \
		2> piscine_php_d05_check/sql_test_dir/errors/$filename.error
	echo 'ex:\t'$filename
	echo $(cat piscine_php_d05_check/sql_test_dir/errors/$filename.error)
	echo $(diff piscine_php_d05_check/sql_test_dir/$filename.out \
		piscine_php_d05_check/sql_test_dir/ref/$filename.out.ref)
done
